-- Active: 1733047699009@@127.0.0.1@3306
CREATE DATABASE QUIZZES;

USE QUIZZES;

-- QUIZ Table
CREATE TABLE QUIZ (
    QUIZ_ID INT NOT NULL CONSTRAINT SevenDigitMax_Constraint CHECK (QUIZ_ID BETWEEN 0 AND 9999999),
    QUIZ_name VARCHAR(30) NOT NULL DEFAULT 'Untitled Quiz',
    QUIZ_score INT,
    QUIZ_type VARCHAR(255),
    QUIZ_subject VARCHAR(255), 
    PRIMARY KEY (QUIZ_ID, QUIZ_name)
);

-- QUESTION_MULTIPLE_CHOICE Table
CREATE TABLE QUESTION_MULTIPLE_CHOICE (
    QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUIZ_ID INT,
    QUIZ_name VARCHAR(30),
    QUESTION VARCHAR(255),
    ANSWER VARCHAR(255),
    FOREIGN KEY (QUIZ_ID, QUIZ_name) REFERENCES QUIZ(QUIZ_ID, QUIZ_name)
);

-- CHOICES_MULTIPLE Table
CREATE TABLE CHOICES_MULTIPLE (
    CHOICE_ID INT AUTO_INCREMENT PRIMARY KEY, 
    QUESTION_ID INT, -- Relating choices to a specific question
    OPTION_A VARCHAR(255),
    OPTION_B VARCHAR(255),
    OPTION_C VARCHAR(255),
    OPTION_D VARCHAR(255),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION_MULTIPLE_CHOICE(QUESTION_ID) 
);

-- IDENTIFICATION Table
CREATE TABLE IDENTIFICATION (
    QUIZ_ID INT,
    QUIZ_name VARCHAR(30),
    QUESTION VARCHAR(255),
    ANSWER VARCHAR(255),
    PRIMARY KEY (QUIZ_ID, QUIZ_name, QUESTION)
);

-- PLAYER_STATS Table
CREATE TABLE PLAYER_STATS (
    PLAYER_ID INT AUTO_INCREMENT PRIMARY KEY, 
    SCORE_average INT,
    PLAY_DATE DATETIME
);





